#!/bin/bash
# =============================================================================
# VisiMon Agent — One-liner Install Script
# Usage: curl -fsSL https://visimon.dev/install.sh | sh
#
# Auto-detects OS and architecture, downloads latest agent binary from GitHub
# releases, installs it as a systemd service, and generates a default config.
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

# ---- Constants ----
REPO_OWNER="Muhammadkafaby"
REPO_NAME="NetStack"
BINARY_NAME="visimon-agent"
CONFIG_DIR="/etc/visimon"
CONFIG_FILE="${CONFIG_DIR}/agent.yaml"
SERVICE_FILE="/etc/systemd/system/visimon-agent.service"
INSTALL_DIR="/usr/local/bin"

# ---- Colors ----
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()  { printf "${BLUE}[INFO]${NC}  %s\n" "$*"; }
ok()    { printf "${GREEN}[OK]${NC}    %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${NC}  %s\n" "$*" >&2; }
fail()  { printf "${RED}[FAIL]${NC}  %s\n" "$*" >&2; exit 1; }

# ---- Pre-flight checks ----
info "VisiMon Agent Installer"
info "========================"
echo ""

# Must be root to install systemd service
if [ "$(id -u)" -ne 0 ]; then
    fail "This installer must be run as root (or with sudo)."
fi

# Detect OS
OS="$(uname -s)"
case "$OS" in
    Linux)  OS="linux" ;;
    Darwin) OS="darwin" ;;
    *)
        fail "Unsupported OS: ${OS}. VisiMon Agent currently supports Linux and macOS."
        ;;
esac

# Detect architecture
ARCH="$(uname -m)"
case "$ARCH" in
    x86_64|amd64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    armv7l|armv6l) ARCH="armv7" ;;
    *)
        fail "Unsupported architecture: ${ARCH}. Supported: amd64, arm64, armv7"
        ;;
esac

ok "Detected: ${OS} / ${ARCH}"

# Check for required tools
command -v curl >/dev/null 2>&1 || fail "curl is required but not installed."
command -v tar >/dev/null 2>&1  || fail "tar is required but not installed."

# ---- Determine latest version ----
info "Fetching latest release version..."
LATEST_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases/latest"
VERSION=$(curl -fsSL "${LATEST_URL}" 2>/dev/null | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')

if [ -z "$VERSION" ]; then
    warn "Could not fetch latest version from GitHub API. Falling back to v0.1.0"
    VERSION="v0.1.0"
fi
ok "Latest version: ${VERSION}"

# ---- Download binary ----
TARBALL="${BINARY_NAME}_${VERSION}_${OS}_${ARCH}.tar.gz"
DOWNLOAD_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/${VERSION}/${TARBALL}"
TMP_DIR=$(mktemp -d)
trap 'rm -rf "${TMP_DIR}"' EXIT

info "Downloading ${BINARY_NAME} ${VERSION}..."
info "  ${DOWNLOAD_URL}"

if ! curl -fsSL "${DOWNLOAD_URL}" -o "${TMP_DIR}/${TARBALL}"; then
    fail "Download failed. URL may not exist yet — try building from source."
fi

info "Extracting..."
tar -xzf "${TMP_DIR}/${TARBALL}" -C "${TMP_DIR}"

# Find the binary (may be named visimon-agent or just visimon-agent)
BINARY_PATH=$(find "${TMP_DIR}" -type f -name "${BINARY_NAME}" 2>/dev/null | head -1)
if [ -z "$BINARY_PATH" ]; then
    # Try without version prefix
    BINARY_PATH=$(find "${TMP_DIR}" -type f -executable 2>/dev/null | head -1)
fi
if [ -z "$BINARY_PATH" ]; then
    fail "Could not find binary in archive."
fi

# Install binary
info "Installing to ${INSTALL_DIR}/${BINARY_NAME}..."
install -m 755 "${BINARY_PATH}" "${INSTALL_DIR}/${BINARY_NAME}"
ok "Binary installed at ${INSTALL_DIR}/${BINARY_NAME}"

# ---- Generate config ----
if [ -f "${CONFIG_FILE}" ]; then
    warn "Config file ${CONFIG_FILE} already exists — not overwriting."
else
    info "Generating config at ${CONFIG_FILE}..."

    # Get server URL from argument or use default
    SERVER_URL="${1:-http://localhost:8080}"

    # Generate a random API key
    API_KEY=$(tr -dc 'a-f0-9' < /dev/urandom | head -c 32 2>/dev/null || echo "change-me")

    mkdir -p "${CONFIG_DIR}"
    cat > "${CONFIG_FILE}" <<-EOF
# VisiMon Agent Configuration
# Generated by install.sh on $(date)

server_url: "${SERVER_URL}"
interval: 1
hostname: "$(hostname)"
api_key: "${API_KEY}"
log_level: "info"
EOF
    ok "Config written to ${CONFIG_FILE}"
fi

# ---- Install systemd service (Linux only) ----
if [ "${OS}" = "linux" ]; then
    info "Installing systemd service..."

    cat > "${SERVICE_FILE}" <<-EOF
[Unit]
Description=VisiMon Agent — Lightweight system metrics collector
Documentation=https://visimon.dev/docs
After=network.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/${BINARY_NAME} --config ${CONFIG_FILE}
Restart=always
RestartSec=5
StartLimitBurst=3
StartLimitInterval=60
# Security hardening
NoNewPrivileges=yes
ProtectSystem=strict
ReadWritePaths=${CONFIG_DIR}
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable visimon-agent.service
    systemctl start visimon-agent.service

    ok "Systemd service installed and started."
    info "  Status: systemctl status visimon-agent.service"
    info "  Logs:   journalctl -u visimon-agent.service -f"
fi

# ---- Summary ----
echo ""
info "=============== Installation Complete ==============="
ok "VisiMon Agent ${VERSION} installed successfully!"
echo ""
info "  Binary:    ${INSTALL_DIR}/${BINARY_NAME}"
info "  Config:    ${CONFIG_FILE}"
info "  Service:   ${SERVICE_FILE}"
echo ""
info "Next steps:"
info "  1. Edit ${CONFIG_FILE} to set your server URL and API key"
info "  2. Restart the service: systemctl restart visimon-agent"
if [ "${OS}" = "darwin" ]; then
    info "  3. Run the agent manually: ${INSTALL_DIR}/${BINARY_NAME} --config ${CONFIG_FILE}"
fi
echo ""
info "For help: visimon-agent --help"
info "====================================================="